pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Generate Jenkins Files') {
            steps {
                sh '''
                python3 scripts/onboard.py projects/blog-app.yml
                '''
            }
        }

        stage('Generate Jobs') {
            steps {

                jobDsl(
                    targets: 'jenkins/jobs/*.groovy',
                    removedJobAction: 'DELETE',
                    removedViewAction: 'DELETE',
                    lookupStrategy: 'JENKINS_ROOT'
                )

            }
        }

    }

    post {

        success {
            echo "Seed Job Completed"
        }

        failure {
            echo "Seed Job Failed"
        }

    }

}